"use client"
import React from 'react';
import { Epilogue } from 'next/font/google';

import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';

import StyledComponentsRegistry from './lib/AntdRegistry';

import { store,persistor } from '@/redux';

import './globals.css';

const font = Epilogue({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


const RootLayout = ({ children }) => {
  return (
  <html lang="en">
    <body className={font.className}>
    <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </PersistGate>
    </Provider>
    </body>
  </html>
)};

export default RootLayout;